export const IMAGE_BASE_URL = 'https://pub-42a385b873274532b0f776d49ed5efc4.r2.dev'

// Cache busting version - update this when images change
const CACHE_VERSION = '20250105';

export const IMAGES = {
    // General Images
    background: `${IMAGE_BASE_URL}/image/background.jpg?v=${CACHE_VERSION}`,
    hero1: `${IMAGE_BASE_URL}/image/hero1.webp?v=${CACHE_VERSION}`,
    hero2: `${IMAGE_BASE_URL}/image/hero2.webp?v=${CACHE_VERSION}`,
    hero3: `${IMAGE_BASE_URL}/image/hero3.webp?v=${CACHE_VERSION}`,
    hero4: `${IMAGE_BASE_URL}/image/hero4.webp?v=${CACHE_VERSION}`,
    hero5: `${IMAGE_BASE_URL}/image/hero5.webp?v=${CACHE_VERSION}`,
    hero6: `${IMAGE_BASE_URL}/image/hero6.webp?v=${CACHE_VERSION}`,
    hero7: `${IMAGE_BASE_URL}/image/hero7.webp?v=${CACHE_VERSION}`,
    intro1: `${IMAGE_BASE_URL}/image/intro1.jpg`,
    intro2: `${IMAGE_BASE_URL}/image/intro2.jpg`,
    intro3: `${IMAGE_BASE_URL}/image/intro3.jpg`,
    logo_rmbg: `${IMAGE_BASE_URL}/image/logo-rmbg.png`,
    logo: `${IMAGE_BASE_URL}/image/logo.png`,
    service: `${IMAGE_BASE_URL}/image/service.jpg`,
    founder1: `${IMAGE_BASE_URL}/image/founder1.webp`,
    founder2: `${IMAGE_BASE_URL}/image/founder2.webp`,

    // Portfolio thumbnails
    nathanxtracy: `${IMAGE_BASE_URL}/image/nathanxtracy.webp`,
    tienxwilliam: `${IMAGE_BASE_URL}/image/tienxwilliam.webp`,
    duyenxsteven: `${IMAGE_BASE_URL}/image/duyenxsteven.webp`,
    vanxtuc: `${IMAGE_BASE_URL}/image/vanxtuc.webp`,
    tranxtai: `${IMAGE_BASE_URL}/image/tranxtai.webp`,
    mayxmat: `${IMAGE_BASE_URL}/image/mayxmat.webp`,
    vietxquynh: `${IMAGE_BASE_URL}/image/vietxquynh.webp`,
    nganxnhat: `${IMAGE_BASE_URL}/image/nganxnhat.webp`,
    duyxmy: `${IMAGE_BASE_URL}/image/duyxmy.webp`,
    trangxvini: `${IMAGE_BASE_URL}/image/trangxvini.webp`,
    eventxbenang: `${IMAGE_BASE_URL}/image/eventxbenang.webp`,
    event1: `${IMAGE_BASE_URL}/image/event1.webp`,
    phuongxhien: `${IMAGE_BASE_URL}/image/phuongxhien.webp`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2_1.webp`,
    phuongxhien3: `${IMAGE_BASE_URL}/image/phuongxhien3_1.webp`,
    elopement: `${IMAGE_BASE_URL}/image/elopement.webp`,
    hieuxbrian: `${IMAGE_BASE_URL}/image/hieuxbrian.webp`,
    hanxtuan: `${IMAGE_BASE_URL}/image/hanxtuan.webp`,
    duyxyen: `${IMAGE_BASE_URL}/image/duyxyen1.webp`,
    thoaxbinh: `${IMAGE_BASE_URL}/image/thoaxbinh1.webp`,
    anxnghi: `${IMAGE_BASE_URL}/image/anxnghi1.webp`,
    anxtoan: `${IMAGE_BASE_URL}/image/anxtoan1.webp`,
    hanxtung: `${IMAGE_BASE_URL}/image/hanxtung1.webp`,
    joshxlinda: `${IMAGE_BASE_URL}/image/joshxlinda1.webp`,
    maimyxtoanem: `${IMAGE_BASE_URL}/image/maimyxtoanem1.webp`,
    nghiaxnguyet: `${IMAGE_BASE_URL}/image/nghiaxnguyet1.webp`,
    thongxhuyen: `${IMAGE_BASE_URL}/image/thongxhuyen1.webp`,
    tramxmax: `${IMAGE_BASE_URL}/image/tramxmax1.webp`,
    tranxtai2: `${IMAGE_BASE_URL}/image/tranxtai2_1.webp`,
    vietxquynh2: `${IMAGE_BASE_URL}/image/vietxquynh2_1.webp`,
    vyxkhang: `${IMAGE_BASE_URL}/image/vyxkhang1.webp`,
    trangxvini: `${IMAGE_BASE_URL}/image/trangxvini1.webp`,
    ngocxshawn: `${IMAGE_BASE_URL}/image/ngocxshawn1.webp`,

    // Nathan x Tracy gallery
    nathanxtracy1: `${IMAGE_BASE_URL}/image/nathanxtracy1.webp`,
    nathanxtracy2: `${IMAGE_BASE_URL}/image/nathanxtracy2.webp`,
    nathanxtracy3: `${IMAGE_BASE_URL}/image/nathanxtracy3.webp`,
    nathanxtracy4: `${IMAGE_BASE_URL}/image/nathanxtracy4.webp`,
    nathanxtracy5: `${IMAGE_BASE_URL}/image/nathanxtracy5.webp`,
    nathanxtracy6: `${IMAGE_BASE_URL}/image/nathanxtracy6.webp`,
    nathanxtracy7: `${IMAGE_BASE_URL}/image/nathanxtracy7.webp`,
    nathanxtracy8: `${IMAGE_BASE_URL}/image/nathanxtracy8.webp`,
    nathanxtracy9: `${IMAGE_BASE_URL}/image/nathanxtracy9.webp`,
    nathanxtracy10: `${IMAGE_BASE_URL}/image/nathanxtracy10.webp`,
    nathanxtracy11: `${IMAGE_BASE_URL}/image/nathanxtracy11.webp`,
    nathanxtracy12: `${IMAGE_BASE_URL}/image/nathanxtracy12.webp`,
    nathanxtracy13: `${IMAGE_BASE_URL}/image/nathanxtracy13.webp`,

    // Tien x William gallery
    tienxwillam1: `${IMAGE_BASE_URL}/image/tienxwillam1.webp`,
    tienxwillam2: `${IMAGE_BASE_URL}/image/tienxwillam2.webp`,
    tienxwillam3: `${IMAGE_BASE_URL}/image/tienxwillam3.webp`,
    tienxwillam4: `${IMAGE_BASE_URL}/image/tienxwillam4.webp`,
    tienxwillam5: `${IMAGE_BASE_URL}/image/tienxwillam5.webp`,
    tienxwillam6: `${IMAGE_BASE_URL}/image/tienxwillam6.webp`,
    tienxwillam7: `${IMAGE_BASE_URL}/image/tienxwillam7.webp`,
    tienxwillam8: `${IMAGE_BASE_URL}/image/tienxwillam8.webp`,
    tienxwillam9: `${IMAGE_BASE_URL}/image/tienxwillam9.webp`,
    tienxwillam10: `${IMAGE_BASE_URL}/image/tienxwillam10.webp`,
    tienxwillam11: `${IMAGE_BASE_URL}/image/tienxwillam11.webp`,
    tienxwillam12: `${IMAGE_BASE_URL}/image/tienxwillam12.webp`,
    tienxwillam13: `${IMAGE_BASE_URL}/image/tienxwillam13.webp`,
    tienxwillam14: `${IMAGE_BASE_URL}/image/tienxwillam14.webp`,
    tienxwillam15: `${IMAGE_BASE_URL}/image/tienxwillam15.webp`,
    tienxwillam16: `${IMAGE_BASE_URL}/image/tienxwillam16.webp`,
    tienxwillam17: `${IMAGE_BASE_URL}/image/tienxwillam17.webp`,
    tienxwillam18: `${IMAGE_BASE_URL}/image/tienxwillam18.webp`,

    // Han x Tuan gallery
    hanxtuan1: `${IMAGE_BASE_URL}/image/hanxtuan1.webp`,
    hanxtuan2: `${IMAGE_BASE_URL}/image/hanxtuan2.webp`,
    hanxtuan3: `${IMAGE_BASE_URL}/image/hanxtuan3.webp`,
    hanxtuan4: `${IMAGE_BASE_URL}/image/hanxtuan4.webp`,
    hanxtuan5: `${IMAGE_BASE_URL}/image/hanxtuan5.webp`,
    hanxtuan6: `${IMAGE_BASE_URL}/image/hanxtuan6.webp`,
    hanxtuan7: `${IMAGE_BASE_URL}/image/hanxtuan7.webp`,
    hanxtuan8: `${IMAGE_BASE_URL}/image/hanxtuan8.webp`,
    hanxtuan9: `${IMAGE_BASE_URL}/image/hanxtuan9.webp`,
    hanxtuan10: `${IMAGE_BASE_URL}/image/hanxtuan10.webp`,
    hanxtuan11: `${IMAGE_BASE_URL}/image/hanxtuan11.webp`,
    hanxtuan12: `${IMAGE_BASE_URL}/image/hanxtuan12.webp`,

    // Duyen x Steven gallery
    duyenxsteven1: `${IMAGE_BASE_URL}/image/duyenxsteven1.webp`,
    duyenxsteven2: `${IMAGE_BASE_URL}/image/duyenxsteven2.webp`,
    duyenxsteven3: `${IMAGE_BASE_URL}/image/duyenxsteven3.webp`,
    duyenxsteven4: `${IMAGE_BASE_URL}/image/duyenxsteven4.webp`,
    duyenxsteven5: `${IMAGE_BASE_URL}/image/duyenxsteven5.webp`,
    duyenxsteven6: `${IMAGE_BASE_URL}/image/duyenxsteven6.webp`,
    duyenxsteven7: `${IMAGE_BASE_URL}/image/duyenxsteven7.webp`,
    duyenxsteven8: `${IMAGE_BASE_URL}/image/duyenxsteven8.webp`,
    duyenxsteven9: `${IMAGE_BASE_URL}/image/duyenxsteven9.webp`,
    duyenxsteven10: `${IMAGE_BASE_URL}/image/duyenxsteven10.webp`,
    duyenxsteven11: `${IMAGE_BASE_URL}/image/duyenxsteven11.webp`,
    duyenxsteven12: `${IMAGE_BASE_URL}/image/duyenxsteven12.webp`,
    duyenxsteven13: `${IMAGE_BASE_URL}/image/duyenxsteven13.webp`,
    duyenxsteven14: `${IMAGE_BASE_URL}/image/duyenxsteven14.webp`,
    duyenxsteven15: `${IMAGE_BASE_URL}/image/duyenxsteven15.webp`,
    duyenxsteven16: `${IMAGE_BASE_URL}/image/duyenxsteven16.webp`,
    duyenxsteven17: `${IMAGE_BASE_URL}/image/duyenxsteven17.webp`,
    duyenxsteven18: `${IMAGE_BASE_URL}/image/duyenxsteven18.webp`,
    duyenxsteven19: `${IMAGE_BASE_URL}/image/duyenxsteven19.webp`,

    // Van x Tuc gallery
    vanxtuc1: `${IMAGE_BASE_URL}/image/vanxtuc1.webp`,
    vanxtuc2: `${IMAGE_BASE_URL}/image/vanxtuc2.webp`,
    vanxtuc3: `${IMAGE_BASE_URL}/image/vanxtuc3.webp`,
    vanxtuc4: `${IMAGE_BASE_URL}/image/vanxtuc4.webp`,
    vanxtuc5: `${IMAGE_BASE_URL}/image/vanxtuc5.webp`,
    vanxtuc6: `${IMAGE_BASE_URL}/image/vanxtuc6.webp`,
    vanxtuc7: `${IMAGE_BASE_URL}/image/vanxtuc7.webp`,
    vanxtuc8: `${IMAGE_BASE_URL}/image/vanxtuc8.webp`,
    vanxtuc9: `${IMAGE_BASE_URL}/image/vanxtuc9.webp`,
    vanxtuc10: `${IMAGE_BASE_URL}/image/vanxtuc10.webp`,
    vanxtuc11: `${IMAGE_BASE_URL}/image/vanxtuc11.webp`,
    vanxtuc12: `${IMAGE_BASE_URL}/image/vanxtuc12.webp`,
    vanxtuc13: `${IMAGE_BASE_URL}/image/vanxtuc13.webp`,
    vanxtuc14: `${IMAGE_BASE_URL}/image/vanxtuc14.webp`,

    // Tran x Tai gallery
    tranxtai1: `${IMAGE_BASE_URL}/image/tranxtai1.webp`,
    tranxtai2: `${IMAGE_BASE_URL}/image/tranxtai2.webp`,
    tranxtai3: `${IMAGE_BASE_URL}/image/tranxtai3.webp`,
    tranxtai4: `${IMAGE_BASE_URL}/image/tranxtai4.webp`,
    tranxtai5: `${IMAGE_BASE_URL}/image/tranxtai5.webp`,
    tranxtai6: `${IMAGE_BASE_URL}/image/tranxtai6.webp`,
    tranxtai7: `${IMAGE_BASE_URL}/image/tranxtai7.webp`,
    tranxtai8: `${IMAGE_BASE_URL}/image/tranxtai8.webp`,
    tranxtai9: `${IMAGE_BASE_URL}/image/tranxtai9.webp`,
    tranxtai10: `${IMAGE_BASE_URL}/image/tranxtai10.webp`,
    tranxtai11: `${IMAGE_BASE_URL}/image/tranxtai11.webp`,
    tranxtai12: `${IMAGE_BASE_URL}/image/tranxtai12.webp`,

    // May x Mat gallery
    mayxmat1: `${IMAGE_BASE_URL}/image/mayxmat1.webp`,
    mayxmat2: `${IMAGE_BASE_URL}/image/mayxmat2.webp`,
    mayxmat3: `${IMAGE_BASE_URL}/image/mayxmat3.webp`,
    mayxmat4: `${IMAGE_BASE_URL}/image/mayxmat4.webp`,
    mayxmat5: `${IMAGE_BASE_URL}/image/mayxmat5.webp`,
    mayxmat6: `${IMAGE_BASE_URL}/image/mayxmat6.webp`,
    mayxmat7: `${IMAGE_BASE_URL}/image/mayxmat7.webp`,
    mayxmat8: `${IMAGE_BASE_URL}/image/mayxmat8.webp`,
    mayxmat9: `${IMAGE_BASE_URL}/image/mayxmat9.webp`,
    mayxmat10: `${IMAGE_BASE_URL}/image/mayxmat10.webp`,
    mayxmat11: `${IMAGE_BASE_URL}/image/mayxmat11.webp`,
    mayxmat12: `${IMAGE_BASE_URL}/image/mayxmat12.webp`,
    mayxmat13: `${IMAGE_BASE_URL}/image/mayxmat13.webp`,
    mayxmat14: `${IMAGE_BASE_URL}/image/mayxmat14.webp`,
    mayxmat15: `${IMAGE_BASE_URL}/image/mayxmat15.webp`,
    mayxmat16: `${IMAGE_BASE_URL}/image/mayxmat16.webp`,
    mayxmat17: `${IMAGE_BASE_URL}/image/mayxmat17.webp`,
    mayxmat18: `${IMAGE_BASE_URL}/image/mayxmat18.webp`,
    mayxmat19: `${IMAGE_BASE_URL}/image/mayxmat19.webp`,
    mayxmat20: `${IMAGE_BASE_URL}/image/mayxmat20.webp`,
    mayxmat21: `${IMAGE_BASE_URL}/image/mayxmat21.webp`,
    mayxmat22: `${IMAGE_BASE_URL}/image/mayxmat22.webp`,
    mayxmat23: `${IMAGE_BASE_URL}/image/mayxmat23.webp`,
    mayxmat24: `${IMAGE_BASE_URL}/image/mayxmat24.webp`,
    mayxmat25: `${IMAGE_BASE_URL}/image/mayxmat25.webp`,
    mayxmat26: `${IMAGE_BASE_URL}/image/mayxmat26.webp`,
    mayxmat27: `${IMAGE_BASE_URL}/image/mayxmat27.webp`,
    mayxmat28: `${IMAGE_BASE_URL}/image/mayxmat28.webp`,
    mayxmat29: `${IMAGE_BASE_URL}/image/mayxmat29.webp`,
    mayxmat30: `${IMAGE_BASE_URL}/image/mayxmat30.webp`,

    // Hieu x Brian gallery
    hieuxbrian1: `${IMAGE_BASE_URL}/image/hieuxbrian1.webp`,
    hieuxbrian2: `${IMAGE_BASE_URL}/image/hieuxbrian2.webp`,
    hieuxbrian3: `${IMAGE_BASE_URL}/image/hieuxbrian3.webp`,
    hieuxbrian4: `${IMAGE_BASE_URL}/image/hieuxbrian4.webp`,
    hieuxbrian5: `${IMAGE_BASE_URL}/image/hieuxbrian5.webp`,
    hieuxbrian6: `${IMAGE_BASE_URL}/image/hieuxbrian6.webp`,
    hieuxbrian7: `${IMAGE_BASE_URL}/image/hieuxbrian7.webp`,
    hieuxbrian8: `${IMAGE_BASE_URL}/image/hieuxbrian8.webp`,
    hieuxbrian9: `${IMAGE_BASE_URL}/image/hieuxbrian9.webp`,
    hieuxbrian10: `${IMAGE_BASE_URL}/image/hieuxbrian10.webp`,
    hieuxbrian11: `${IMAGE_BASE_URL}/image/hieuxbrian11.webp`,
    hieuxbrian12: `${IMAGE_BASE_URL}/image/hieuxbrian12.webp`,
    hieuxbrian13: `${IMAGE_BASE_URL}/image/hieuxbrian13.webp`,
    hieuxbrian14: `${IMAGE_BASE_URL}/image/hieuxbrian14.webp`,
    hieuxbrian15: `${IMAGE_BASE_URL}/image/hieuxbrian15.webp`,
    hieuxbrian16: `${IMAGE_BASE_URL}/image/hieuxbrian16.webp`,

    // Duy x My gallery
    duyxmy1: `${IMAGE_BASE_URL}/image/duyxmy1.webp`,
    duyxmy2: `${IMAGE_BASE_URL}/image/duyxmy2.webp`,
    duyxmy3: `${IMAGE_BASE_URL}/image/duyxmy3.webp`,
    duyxmy4: `${IMAGE_BASE_URL}/image/duyxmy4.webp`,
    duyxmy5: `${IMAGE_BASE_URL}/image/duyxmy5.webp`,
    duyxmy6: `${IMAGE_BASE_URL}/image/duyxmy6.webp`,
    duyxmy7: `${IMAGE_BASE_URL}/image/duyxmy7.webp`,
    duyxmy8: `${IMAGE_BASE_URL}/image/duyxmy8.webp`,
    duyxmy9: `${IMAGE_BASE_URL}/image/duyxmy9.webp`,
    duyxmy10: `${IMAGE_BASE_URL}/image/duyxmy10.webp`,
    duyxmy11: `${IMAGE_BASE_URL}/image/duyxmy11.webp`,
    duyxmy12: `${IMAGE_BASE_URL}/image/duyxmy12.webp`,
    duyxmy13: `${IMAGE_BASE_URL}/image/duyxmy13.webp`,
    duyxmy14: `${IMAGE_BASE_URL}/image/duyxmy14.webp`,
    duyxmy15: `${IMAGE_BASE_URL}/image/duyxmy15.webp`,
    duyxmy16: `${IMAGE_BASE_URL}/image/duyxmy16.webp`,
    duyxmy17: `${IMAGE_BASE_URL}/image/duyxmy17.webp`,
    duyxmy18: `${IMAGE_BASE_URL}/image/duyxmy18.webp`,
    duyxmy19: `${IMAGE_BASE_URL}/image/duyxmy19.webp`,
    duyxmy20: `${IMAGE_BASE_URL}/image/duyxmy20.webp`,

    // Phuong x Hien gallery
    phuongxhien1: `${IMAGE_BASE_URL}/image/phuongxhien1.webp`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2.webp`,
    phuongxhien3: `${IMAGE_BASE_URL}/image/phuongxhien3.webp`,
    phuongxhien4: `${IMAGE_BASE_URL}/image/phuongxhien4.webp`,
    phuongxhien5: `${IMAGE_BASE_URL}/image/phuongxhien5.webp`,
    phuongxhien6: `${IMAGE_BASE_URL}/image/phuongxhien6.webp`,
    phuongxhien7: `${IMAGE_BASE_URL}/image/phuongxhien7.webp`,
    phuongxhien8: `${IMAGE_BASE_URL}/image/phuongxhien8.webp`,
    phuongxhien9: `${IMAGE_BASE_URL}/image/phuongxhien9.webp`,
    phuongxhien10: `${IMAGE_BASE_URL}/image/phuongxhien10.webp`,
    phuongxhien11: `${IMAGE_BASE_URL}/image/phuongxhien11.webp`,
    phuongxhien12: `${IMAGE_BASE_URL}/image/phuongxhien12.webp`,
    phuongxhien13: `${IMAGE_BASE_URL}/image/phuongxhien13.webp`,
    phuongxhien14: `${IMAGE_BASE_URL}/image/phuongxhien14.webp`,
    phuongxhien17: `${IMAGE_BASE_URL}/image/phuongxhien17.webp`,
    phuongxhien18: `${IMAGE_BASE_URL}/image/phuongxhien18.webp`,
    phuongxhien19: `${IMAGE_BASE_URL}/image/phuongxhien19.webp`,
    phuongxhien20: `${IMAGE_BASE_URL}/image/phuongxhien20.webp`,
    phuongxhien21: `${IMAGE_BASE_URL}/image/phuongxhien21.webp`,

    // Phuong x Hien 2 gallery
    phuongxhien2_1: `${IMAGE_BASE_URL}/image/phuongxhien2.1.webp`,
    phuongxhien2_2: `${IMAGE_BASE_URL}/image/phuongxhien2.2.webp`,
    phuongxhien2_3: `${IMAGE_BASE_URL}/image/phuongxhien2.3.webp`,
    phuongxhien2_4: `${IMAGE_BASE_URL}/image/phuongxhien2.4.webp`,
    phuongxhien2_5: `${IMAGE_BASE_URL}/image/phuongxhien2.5.webp`,
    phuongxhien2_6: `${IMAGE_BASE_URL}/image/phuongxhien2.6.webp`,
    phuongxhien2_7: `${IMAGE_BASE_URL}/image/phuongxhien2.7.webp`,
    phuongxhien2_8: `${IMAGE_BASE_URL}/image/phuongxhien2.8.webp`,
    phuongxhien2_9: `${IMAGE_BASE_URL}/image/phuongxhien2.9.webp`,
    phuongxhien2_10: `${IMAGE_BASE_URL}/image/phuongxhien2.10.webp`,
    phuongxhien2_11: `${IMAGE_BASE_URL}/image/phuongxhien2.11.webp`,
    phuongxhien2_12: `${IMAGE_BASE_URL}/image/phuongxhien2.12.webp`,
    phuongxhien2_13: `${IMAGE_BASE_URL}/image/phuongxhien2.13.webp`,
    phuongxhien2_14: `${IMAGE_BASE_URL}/image/phuongxhien2.14.webp`,

    // Phuong x Hien 3_ gallery
    phuongxhien3_1: `${IMAGE_BASE_URL}/image/phuongxhien3_1.webp`,
    phuongxhien3_2: `${IMAGE_BASE_URL}/image/phuongxhien3_2.webp`,
    phuongxhien3_3: `${IMAGE_BASE_URL}/image/phuongxhien3_3.webp`,
    phuongxhien3_4: `${IMAGE_BASE_URL}/image/phuongxhien3_4.webp`,
    phuongxhien3_5: `${IMAGE_BASE_URL}/image/phuongxhien3_5.webp`,
    phuongxhien3_6: `${IMAGE_BASE_URL}/image/phuongxhien3_6.webp`,
    phuongxhien3_7: `${IMAGE_BASE_URL}/image/phuongxhien3_7.webp`,
    phuongxhien3_8: `${IMAGE_BASE_URL}/image/phuongxhien3_8.webp`,
    phuongxhien3_9: `${IMAGE_BASE_URL}/image/phuongxhien3_9.webp`,
    phuongxhien3_10: `${IMAGE_BASE_URL}/image/phuongxhien3_10.webp`,
    phuongxhien3_11: `${IMAGE_BASE_URL}/image/phuongxhien3_11.webp`,
    phuongxhien3_12: `${IMAGE_BASE_URL}/image/phuongxhien3_12.webp`,
    phuongxhien3_13: `${IMAGE_BASE_URL}/image/phuongxhien3_13.webp`,
    phuongxhien3_14: `${IMAGE_BASE_URL}/image/phuongxhien3_14.webp`,
    phuongxhien3_15: `${IMAGE_BASE_URL}/image/phuongxhien3_15.webp`,
    phuongxhien3_16: `${IMAGE_BASE_URL}/image/phuongxhien3_16.webp`,
    phuongxhien3_17: `${IMAGE_BASE_URL}/image/phuongxhien3_17.webp`,
    phuongxhien3_18: `${IMAGE_BASE_URL}/image/phuongxhien3_18.webp`,
    phuongxhien3_19: `${IMAGE_BASE_URL}/image/phuongxhien3_19.webp`,
    phuongxhien3_20: `${IMAGE_BASE_URL}/image/phuongxhien3_20.webp`,
    phuongxhien3_21: `${IMAGE_BASE_URL}/image/phuongxhien3_21.webp`,

    // Elopment gallery
    elopement1: `${IMAGE_BASE_URL}/image/elopement1.webp`,
    elopement2: `${IMAGE_BASE_URL}/image/elopement2.webp`,
    elopement3: `${IMAGE_BASE_URL}/image/elopement3.webp`,
    elopement4: `${IMAGE_BASE_URL}/image/elopement4.webp`,
    elopement5: `${IMAGE_BASE_URL}/image/elopement5.webp`,
    elopement6: `${IMAGE_BASE_URL}/image/elopement6.webp`,
    elopement7: `${IMAGE_BASE_URL}/image/elopement7.webp`,
    elopement8: `${IMAGE_BASE_URL}/image/elopement8.webp`,
    elopement9: `${IMAGE_BASE_URL}/image/elopement9.webp`,
    elopement10: `${IMAGE_BASE_URL}/image/elopement10.webp`,
    elopement11: `${IMAGE_BASE_URL}/image/elopement11.webp`,
    elopement12: `${IMAGE_BASE_URL}/image/elopement12.webp`,
    elopement13: `${IMAGE_BASE_URL}/image/elopement13.webp`,
    elopement14: `${IMAGE_BASE_URL}/image/elopement14.webp`,
    elopement15: `${IMAGE_BASE_URL}/image/elopement15.webp`,
    elopement16: `${IMAGE_BASE_URL}/image/elopement16.webp`,

    // Duy x Yen gallery
    duyxyen1: `${IMAGE_BASE_URL}/image/duyxyen1.webp`,
    duyxyen2: `${IMAGE_BASE_URL}/image/duyxyen2.webp`,
    duyxyen3: `${IMAGE_BASE_URL}/image/duyxyen3.webp`,
    duyxyen4: `${IMAGE_BASE_URL}/image/duyxyen4.webp`,
    duyxyen5: `${IMAGE_BASE_URL}/image/duyxyen5.webp`,
    duyxyen6: `${IMAGE_BASE_URL}/image/duyxyen6.webp`,
    duyxyen7: `${IMAGE_BASE_URL}/image/duyxyen7.webp`,
    duyxyen8: `${IMAGE_BASE_URL}/image/duyxyen8.webp`,
    duyxyen9: `${IMAGE_BASE_URL}/image/duyxyen9.webp`,
    duyxyen10: `${IMAGE_BASE_URL}/image/duyxyen10.webp`,
    duyxyen11: `${IMAGE_BASE_URL}/image/duyxyen11.webp`,
    duyxyen12: `${IMAGE_BASE_URL}/image/duyxyen12.webp`,

    // Thoa x Binh gallery
    thoaxbinh1: `${IMAGE_BASE_URL}/image/thoaxbinh1.webp`,
    thoaxbinh2: `${IMAGE_BASE_URL}/image/thoaxbinh2.webp`,
    thoaxbinh3: `${IMAGE_BASE_URL}/image/thoaxbinh3.webp`,
    thoaxbinh4: `${IMAGE_BASE_URL}/image/thoaxbinh4.webp`,
    thoaxbinh5: `${IMAGE_BASE_URL}/image/thoaxbinh5.webp`,
    thoaxbinh6: `${IMAGE_BASE_URL}/image/thoaxbinh6.webp`,
    thoaxbinh7: `${IMAGE_BASE_URL}/image/thoaxbinh7.webp`,
    thoaxbinh8: `${IMAGE_BASE_URL}/image/thoaxbinh8.webp`,
    thoaxbinh9: `${IMAGE_BASE_URL}/image/thoaxbinh9.webp`,
    thoaxbinh10: `${IMAGE_BASE_URL}/image/thoaxbinh10.webp`,
    thoaxbinh11: `${IMAGE_BASE_URL}/image/thoaxbinh11.webp`,
    thoaxbinh12: `${IMAGE_BASE_URL}/image/thoaxbinh12.webp`,
    thoaxbinh13: `${IMAGE_BASE_URL}/image/thoaxbinh13.webp`,
    thoaxbinh14: `${IMAGE_BASE_URL}/image/thoaxbinh14.webp`,
    thoaxbinh15: `${IMAGE_BASE_URL}/image/thoaxbinh15.webp`,
    thoaxbinh16: `${IMAGE_BASE_URL}/image/thoaxbinh16.webp`,

    // An x Nghi gallery
    anxnghi1: `${IMAGE_BASE_URL}/image/anxnghi1.webp`,
    anxnghi2: `${IMAGE_BASE_URL}/image/anxnghi2.webp`,
    anxnghi3: `${IMAGE_BASE_URL}/image/anxnghi3.webp`,
    anxnghi4: `${IMAGE_BASE_URL}/image/anxnghi4.webp`,
    anxnghi5: `${IMAGE_BASE_URL}/image/anxnghi5.webp`,
    anxnghi6: `${IMAGE_BASE_URL}/image/anxnghi6.webp`,
    anxnghi7: `${IMAGE_BASE_URL}/image/anxnghi7.webp`,
    anxnghi8: `${IMAGE_BASE_URL}/image/anxnghi8.webp`,
    anxnghi9: `${IMAGE_BASE_URL}/image/anxnghi9.webp`,
    anxnghi10: `${IMAGE_BASE_URL}/image/anxnghi10.webp`,
    anxnghi11: `${IMAGE_BASE_URL}/image/anxnghi11.webp`,
    anxnghi12: `${IMAGE_BASE_URL}/image/anxnghi12.webp`,
    anxnghi13: `${IMAGE_BASE_URL}/image/anxnghi13.webp`,
    anxnghi14: `${IMAGE_BASE_URL}/image/anxnghi14.webp`,
    anxnghi15: `${IMAGE_BASE_URL}/image/anxnghi15.webp`,
    anxnghi16: `${IMAGE_BASE_URL}/image/anxnghi16.webp`,
    anxnghi17: `${IMAGE_BASE_URL}/image/anxnghi17.webp`,
    anxnghi18: `${IMAGE_BASE_URL}/image/anxnghi18.webp`,
    anxnghi19: `${IMAGE_BASE_URL}/image/anxnghi19.webp`,

    // An x Toan gallery
    anxtoan1: `${IMAGE_BASE_URL}/image/anxtoan1.webp`,
    anxtoan2: `${IMAGE_BASE_URL}/image/anxtoan2.webp`,
    anxtoan3: `${IMAGE_BASE_URL}/image/anxtoan3.webp`,
    anxtoan4: `${IMAGE_BASE_URL}/image/anxtoan4.webp`,
    anxtoan5: `${IMAGE_BASE_URL}/image/anxtoan5.webp`,
    anxtoan6: `${IMAGE_BASE_URL}/image/anxtoan6.webp`,
    anxtoan7: `${IMAGE_BASE_URL}/image/anxtoan7.webp`,

    // Han x Tung gallery
    hanxtung1: `${IMAGE_BASE_URL}/image/hanxtung1.webp`,
    hanxtung2: `${IMAGE_BASE_URL}/image/hanxtung2.webp`,
    hanxtung3: `${IMAGE_BASE_URL}/image/hanxtung3.webp`,
    hanxtung4: `${IMAGE_BASE_URL}/image/hanxtung4.webp`,
    hanxtung5: `${IMAGE_BASE_URL}/image/hanxtung5.webp`,
    hanxtung6: `${IMAGE_BASE_URL}/image/hanxtung6.webp`,
    hanxtung7: `${IMAGE_BASE_URL}/image/hanxtung7.webp`,
    hanxtung8: `${IMAGE_BASE_URL}/image/hanxtung8.webp`,
    hanxtung9: `${IMAGE_BASE_URL}/image/hanxtung9.webp`,
    hanxtung10: `${IMAGE_BASE_URL}/image/hanxtung10.webp`,
    hanxtung11: `${IMAGE_BASE_URL}/image/hanxtung11.webp`,
    hanxtung12: `${IMAGE_BASE_URL}/image/hanxtung12.webp`,
    hanxtung13: `${IMAGE_BASE_URL}/image/hanxtung13.webp`,
    hanxtung14: `${IMAGE_BASE_URL}/image/hanxtung14.webp`,
    hanxtung15: `${IMAGE_BASE_URL}/image/hanxtung15.webp`,
    hanxtung16: `${IMAGE_BASE_URL}/image/hanxtung16.webp`,
    hanxtung17: `${IMAGE_BASE_URL}/image/hanxtung17.webp`,
    hanxtung18: `${IMAGE_BASE_URL}/image/hanxtung18.webp`,
    hanxtung19: `${IMAGE_BASE_URL}/image/hanxtung19.webp`,
    hanxtung20: `${IMAGE_BASE_URL}/image/hanxtung20.webp`,

    // Josh x Linda gallery
    joshxlinda1: `${IMAGE_BASE_URL}/image/joshxlinda1.webp`,
    joshxlinda2: `${IMAGE_BASE_URL}/image/joshxlinda2.webp`,
    joshxlinda3: `${IMAGE_BASE_URL}/image/joshxlinda3.webp`,
    joshxlinda4: `${IMAGE_BASE_URL}/image/joshxlinda4.webp`,
    joshxlinda5: `${IMAGE_BASE_URL}/image/joshxlinda5.webp`,
    joshxlinda6: `${IMAGE_BASE_URL}/image/joshxlinda6.webp`,
    joshxlinda7: `${IMAGE_BASE_URL}/image/joshxlinda7.webp`,
    joshxlinda8: `${IMAGE_BASE_URL}/image/joshxlinda8.webp`,
    joshxlinda9: `${IMAGE_BASE_URL}/image/joshxlinda9.webp`,
    joshxlinda10: `${IMAGE_BASE_URL}/image/joshxlinda10.webp`,
    joshxlinda11: `${IMAGE_BASE_URL}/image/joshxlinda11.webp`,
    joshxlinda12: `${IMAGE_BASE_URL}/image/joshxlinda12.webp`,
    joshxlinda13: `${IMAGE_BASE_URL}/image/joshxlinda13.webp`,
    joshxlinda14: `${IMAGE_BASE_URL}/image/joshxlinda14.webp`,

    // Mai My x Toan Em gallery
    maimyxtoanem1: `${IMAGE_BASE_URL}/image/maimyxtoanem1.webp`,
    maimyxtoanem2: `${IMAGE_BASE_URL}/image/maimyxtoanem2.webp`,
    maimyxtoanem3: `${IMAGE_BASE_URL}/image/maimyxtoanem3.webp`,
    maimyxtoanem4: `${IMAGE_BASE_URL}/image/maimyxtoanem4.webp`,
    maimyxtoanem5: `${IMAGE_BASE_URL}/image/maimyxtoanem5.webp`,
    maimyxtoanem6: `${IMAGE_BASE_URL}/image/maimyxtoanem6.webp`,
    maimyxtoanem7: `${IMAGE_BASE_URL}/image/maimyxtoanem7.webp`,
    maimyxtoanem8: `${IMAGE_BASE_URL}/image/maimyxtoanem8.webp`,
    maimyxtoanem9: `${IMAGE_BASE_URL}/image/maimyxtoanem9.webp`,
    maimyxtoanem10: `${IMAGE_BASE_URL}/image/maimyxtoanem10.webp`,
    maimyxtoanem11: `${IMAGE_BASE_URL}/image/maimyxtoanem11.webp`,
    maimyxtoanem12: `${IMAGE_BASE_URL}/image/maimyxtoanem12.webp`,
    maimyxtoanem13: `${IMAGE_BASE_URL}/image/maimyxtoanem13.webp`,

    // Ngan x Nhat gallery
    nganxnhat1: `${IMAGE_BASE_URL}/image/nganxnhat1.webp`,
    nganxnhat2: `${IMAGE_BASE_URL}/image/nganxnhat2.webp`,
    nganxnhat3: `${IMAGE_BASE_URL}/image/nganxnhat3.webp`,
    nganxnhat4: `${IMAGE_BASE_URL}/image/nganxnhat4.webp`,
    nganxnhat5: `${IMAGE_BASE_URL}/image/nganxnhat5.webp`,
    nganxnhat6: `${IMAGE_BASE_URL}/image/nganxnhat6.webp`,
    nganxnhat7: `${IMAGE_BASE_URL}/image/nganxnhat7.webp`,
    nganxnhat8: `${IMAGE_BASE_URL}/image/nganxnhat8.webp`,
    nganxnhat9: `${IMAGE_BASE_URL}/image/nganxnhat9.webp`,
    nganxnhat10: `${IMAGE_BASE_URL}/image/nganxnhat10.webp`,
    nganxnhat11: `${IMAGE_BASE_URL}/image/nganxnhat11.webp`,
    nganxnhat12: `${IMAGE_BASE_URL}/image/nganxnhat12.webp`,
    nganxnhat13: `${IMAGE_BASE_URL}/image/nganxnhat13.webp`,
    nganxnhat14: `${IMAGE_BASE_URL}/image/nganxnhat14.webp`,
    nganxnhat15: `${IMAGE_BASE_URL}/image/nganxnhat15.webp`,
    nganxnhat16: `${IMAGE_BASE_URL}/image/nganxnhat16.webp`,
    nganxnhat17: `${IMAGE_BASE_URL}/image/nganxnhat17.webp`,

    // Nghia x Nguyet gallery
    nghiaxnguyet1: `${IMAGE_BASE_URL}/image/nghiaxnguyet1.webp`,
    nghiaxnguyet2: `${IMAGE_BASE_URL}/image/nghiaxnguyet2.webp`,
    nghiaxnguyet3: `${IMAGE_BASE_URL}/image/nghiaxnguyet3.webp`,
    nghiaxnguyet4: `${IMAGE_BASE_URL}/image/nghiaxnguyet4.webp`,
    nghiaxnguyet5: `${IMAGE_BASE_URL}/image/nghiaxnguyet5.webp`,
    nghiaxnguyet6: `${IMAGE_BASE_URL}/image/nghiaxnguyet6.webp`,
    nghiaxnguyet7: `${IMAGE_BASE_URL}/image/nghiaxnguyet7.webp`,
    nghiaxnguyet8: `${IMAGE_BASE_URL}/image/nghiaxnguyet8.webp`,
    nghiaxnguyet9: `${IMAGE_BASE_URL}/image/nghiaxnguyet9.webp`,
    nghiaxnguyet10: `${IMAGE_BASE_URL}/image/nghiaxnguyet10.webp`,
    nghiaxnguyet11: `${IMAGE_BASE_URL}/image/nghiaxnguyet11.webp`,
    nghiaxnguyet12: `${IMAGE_BASE_URL}/image/nghiaxnguyet12.webp`,
    nghiaxnguyet13: `${IMAGE_BASE_URL}/image/nghiaxnguyet13.webp`,
    nghiaxnguyet14: `${IMAGE_BASE_URL}/image/nghiaxnguyet14.webp`,
    nghiaxnguyet15: `${IMAGE_BASE_URL}/image/nghiaxnguyet15.webp`,

    // Thong x Huyen gallery
    thongxhuyen1: `${IMAGE_BASE_URL}/image/thongxhuyen1.webp`,
    thongxhuyen2: `${IMAGE_BASE_URL}/image/thongxhuyen2.webp`,
    thongxhuyen3: `${IMAGE_BASE_URL}/image/thongxhuyen3.webp`,
    thongxhuyen4: `${IMAGE_BASE_URL}/image/thongxhuyen4.webp`,
    thongxhuyen5: `${IMAGE_BASE_URL}/image/thongxhuyen5.webp`,
    thongxhuyen6: `${IMAGE_BASE_URL}/image/thongxhuyen6.webp`,
    thongxhuyen7: `${IMAGE_BASE_URL}/image/thongxhuyen7.webp`,
    thongxhuyen8: `${IMAGE_BASE_URL}/image/thongxhuyen8.webp`,
    thongxhuyen9: `${IMAGE_BASE_URL}/image/thongxhuyen9.webp`,
    thongxhuyen10: `${IMAGE_BASE_URL}/image/thongxhuyen10.webp`,
    thongxhuyen11: `${IMAGE_BASE_URL}/image/thongxhuyen11.webp`,
    thongxhuyen12: `${IMAGE_BASE_URL}/image/thongxhuyen12.webp`,
    thongxhuyen13: `${IMAGE_BASE_URL}/image/thongxhuyen13.webp`,
    thongxhuyen14: `${IMAGE_BASE_URL}/image/thongxhuyen14.webp`,
    thongxhuyen15: `${IMAGE_BASE_URL}/image/thongxhuyen15.webp`,
    thongxhuyen16: `${IMAGE_BASE_URL}/image/thongxhuyen16.webp`,
    thongxhuyen17: `${IMAGE_BASE_URL}/image/thongxhuyen17.webp`,
    thongxhuyen18: `${IMAGE_BASE_URL}/image/thongxhuyen18.webp`,
    thongxhuyen19: `${IMAGE_BASE_URL}/image/thongxhuyen19.webp`,

    // Tram x Max gallery
    tramxmax1: `${IMAGE_BASE_URL}/image/tramxmax1.webp`,
    tramxmax2: `${IMAGE_BASE_URL}/image/tramxmax2.webp`,
    tramxmax3: `${IMAGE_BASE_URL}/image/tramxmax3.webp`,
    tramxmax4: `${IMAGE_BASE_URL}/image/tramxmax4.webp`,
    tramxmax5: `${IMAGE_BASE_URL}/image/tramxmax5.webp`,
    tramxmax6: `${IMAGE_BASE_URL}/image/tramxmax6.webp`,
    tramxmax7: `${IMAGE_BASE_URL}/image/tramxmax7.webp`,
    tramxmax8: `${IMAGE_BASE_URL}/image/tramxmax8.webp`,
    tramxmax9: `${IMAGE_BASE_URL}/image/tramxmax9.webp`,
    tramxmax10: `${IMAGE_BASE_URL}/image/tramxmax10.webp`,
    tramxmax11: `${IMAGE_BASE_URL}/image/tramxmax11.webp`,
    tramxmax12: `${IMAGE_BASE_URL}/image/tramxmax12.webp`,
    tramxmax13: `${IMAGE_BASE_URL}/image/tramxmax13.webp`,
    tramxmax14: `${IMAGE_BASE_URL}/image/tramxmax14.webp`,
    tramxmax15: `${IMAGE_BASE_URL}/image/tramxmax15.webp`,
    tramxmax16: `${IMAGE_BASE_URL}/image/tramxmax16.webp`,
    tramxmax17: `${IMAGE_BASE_URL}/image/tramxmax17.webp`,
    tramxmax18: `${IMAGE_BASE_URL}/image/tramxmax18.webp`,
    tramxmax19: `${IMAGE_BASE_URL}/image/tramxmax19.webp`,

    // Viet  x Quynh gallery
    vietxquynh1: `${IMAGE_BASE_URL}/image/vietxquynh1.webp`,
    vietxquynh2: `${IMAGE_BASE_URL}/image/vietxquynh2.webp`,
    vietxquynh3: `${IMAGE_BASE_URL}/image/vietxquynh3.webp`,
    vietxquynh4: `${IMAGE_BASE_URL}/image/vietxquynh4.webp`,
    vietxquynh5: `${IMAGE_BASE_URL}/image/vietxquynh5.webp`,
    vietxquynh6: `${IMAGE_BASE_URL}/image/vietxquynh6.webp`,
    vietxquynh7: `${IMAGE_BASE_URL}/image/vietxquynh7.webp`,
    vietxquynh8: `${IMAGE_BASE_URL}/image/vietxquynh8.webp`,
    vietxquynh9: `${IMAGE_BASE_URL}/image/vietxquynh9.webp`,
    vietxquynh10: `${IMAGE_BASE_URL}/image/vietxquynh10.webp`,
    vietxquynh11: `${IMAGE_BASE_URL}/image/vietxquynh11.webp`,
    vietxquynh12: `${IMAGE_BASE_URL}/image/vietxquynh12.webp`,
    vietxquynh13: `${IMAGE_BASE_URL}/image/vietxquynh13.webp`,
    vietxquynh14: `${IMAGE_BASE_URL}/image/vietxquynh14.webp`,
    vietxquynh15: `${IMAGE_BASE_URL}/image/vietxquynh15.webp`,
    vietxquynh16: `${IMAGE_BASE_URL}/image/vietxquynh16.webp`,

    // Viet x Quynh 2_ gallery
    vietxquynh2_1: `${IMAGE_BASE_URL}/image/vietxquynh2_1.webp`,
    vietxquynh2_2: `${IMAGE_BASE_URL}/image/vietxquynh2_2.webp`,
    vietxquynh2_3: `${IMAGE_BASE_URL}/image/vietxquynh2_3.webp`,
    vietxquynh2_4: `${IMAGE_BASE_URL}/image/vietxquynh2_4.webp`,
    vietxquynh2_5: `${IMAGE_BASE_URL}/image/vietxquynh2_5.webp`,
    vietxquynh2_6: `${IMAGE_BASE_URL}/image/vietxquynh2_6.webp`,
    vietxquynh2_7: `${IMAGE_BASE_URL}/image/vietxquynh2_7.webp`,
    vietxquynh2_8: `${IMAGE_BASE_URL}/image/vietxquynh2_8.webp`,
    vietxquynh2_9: `${IMAGE_BASE_URL}/image/vietxquynh2_9.webp`,
    vietxquynh2_10: `${IMAGE_BASE_URL}/image/vietxquynh2_10.webp`,
    vietxquynh2_11: `${IMAGE_BASE_URL}/image/vietxquynh2_11.webp`,

    // Tran x Tai 2_ Team gallery
    tranxtai2_1: `${IMAGE_BASE_URL}/image/tranxtai2_1.webp`,
    tranxtai2_2: `${IMAGE_BASE_URL}/image/tranxtai2_2.webp`,
    tranxtai2_3: `${IMAGE_BASE_URL}/image/tranxtai2_3.webp`,
    tranxtai2_4: `${IMAGE_BASE_URL}/image/tranxtai2_4.webp`,
    tranxtai2_5: `${IMAGE_BASE_URL}/image/tranxtai2_5.webp`,
    tranxtai2_6: `${IMAGE_BASE_URL}/image/tranxtai2_6.webp`,
    tranxtai2_7: `${IMAGE_BASE_URL}/image/tranxtai2_7.webp`,
    tranxtai2_8: `${IMAGE_BASE_URL}/image/tranxtai2_8.webp`,

    // Vy x Khang gallery
    vyxkhang1: `${IMAGE_BASE_URL}/image/vyxkhang1.webp`,
    vyxkhang2: `${IMAGE_BASE_URL}/image/vyxkhang2.webp`,
    vyxkhang3: `${IMAGE_BASE_URL}/image/vyxkhang3.webp`,
    vyxkhang4: `${IMAGE_BASE_URL}/image/vyxkhang4.webp`,
    vyxkhang5: `${IMAGE_BASE_URL}/image/vyxkhang5.webp`,
    vyxkhang6: `${IMAGE_BASE_URL}/image/vyxkhang6.webp`,
    vyxkhang7: `${IMAGE_BASE_URL}/image/vyxkhang7.webp`,
    vyxkhang8: `${IMAGE_BASE_URL}/image/vyxkhang8.webp`,
    vyxkhang9: `${IMAGE_BASE_URL}/image/vyxkhang9.webp`,

    // Duy x My 2_ gallery
    duyxmy2_1: `${IMAGE_BASE_URL}/image/duyxmy2_1.webp`,
    duyxmy2_2: `${IMAGE_BASE_URL}/image/duyxmy2_2.webp`,
    duyxmy2_3: `${IMAGE_BASE_URL}/image/duyxmy2_3.webp`,
    duyxmy2_4: `${IMAGE_BASE_URL}/image/duyxmy2_4.webp`,
    duyxmy2_5: `${IMAGE_BASE_URL}/image/duyxmy2_5.webp`,
    duyxmy2_6: `${IMAGE_BASE_URL}/image/duyxmy2_6.webp`,
    duyxmy2_7: `${IMAGE_BASE_URL}/image/duyxmy2_7.webp`,
    duyxmy2_8: `${IMAGE_BASE_URL}/image/duyxmy2_8.webp`,
    duyxmy2_9: `${IMAGE_BASE_URL}/image/duyxmy2_9.webp`,
    duyxmy2_10: `${IMAGE_BASE_URL}/image/duyxmy2_10.webp`,

    // Be Nang gallery
    benang1: `${IMAGE_BASE_URL}/image/benang1.webp`,
    benang2: `${IMAGE_BASE_URL}/image/benang2.webp`,
    benang3: `${IMAGE_BASE_URL}/image/benang3.webp`,
    benang4: `${IMAGE_BASE_URL}/image/benang4.webp`,
    benang5: `${IMAGE_BASE_URL}/image/benang5.webp`,
    benang6: `${IMAGE_BASE_URL}/image/benang6.webp`,
    benang7: `${IMAGE_BASE_URL}/image/benang7.webp`,
    benang8: `${IMAGE_BASE_URL}/image/benang8.webp`,
    benang9: `${IMAGE_BASE_URL}/image/benang9.webp`,
    benang10: `${IMAGE_BASE_URL}/image/benang10.webp`,

    // Trang x Vini gallery
    trangxvini1: `${IMAGE_BASE_URL}/image/trangxvini1.webp`,
    trangxvini2: `${IMAGE_BASE_URL}/image/trangxvini2.webp`,
    trangxvini3: `${IMAGE_BASE_URL}/image/trangxvini3.webp`,
    trangxvini4: `${IMAGE_BASE_URL}/image/trangxvini4.webp`,
    trangxvini5: `${IMAGE_BASE_URL}/image/trangxvini5.webp`,
    trangxvini6: `${IMAGE_BASE_URL}/image/trangxvini6.webp`,
    trangxvini7: `${IMAGE_BASE_URL}/image/trangxvini7.webp`,
    trangxvini8: `${IMAGE_BASE_URL}/image/trangxvini8.webp`,
    trangxvini9: `${IMAGE_BASE_URL}/image/trangxvini9.webp`,
    trangxvini10: `${IMAGE_BASE_URL}/image/trangxvini10.webp`,
    trangxvini11: `${IMAGE_BASE_URL}/image/trangxvini11.webp`,
    trangxvini12: `${IMAGE_BASE_URL}/image/trangxvini12.webp`,
    trangxvini13: `${IMAGE_BASE_URL}/image/trangxvini13.webp`,
    trangxvini14: `${IMAGE_BASE_URL}/image/trangxvini14.webp`,
    trangxvini15: `${IMAGE_BASE_URL}/image/trangxvini15.webp`,
    trangxvini16: `${IMAGE_BASE_URL}/image/trangxvini16.webp`,
    trangxvini17: `${IMAGE_BASE_URL}/image/trangxvini17.webp`,
    trangxvini18: `${IMAGE_BASE_URL}/image/trangxvini18.webp`,
    trangxvini19: `${IMAGE_BASE_URL}/image/trangxvini19.webp`,
    trangxvini20: `${IMAGE_BASE_URL}/image/trangxvini20.webp`,
    trangxvini21: `${IMAGE_BASE_URL}/image/trangxvini21.webp`,

    // Ngoc x Shawn gallery
    ngocxshawn1: `${IMAGE_BASE_URL}/image/ngocxshawn1.webp`,
    ngocxshawn2: `${IMAGE_BASE_URL}/image/ngocxshawn2.webp`,
    ngocxshawn3: `${IMAGE_BASE_URL}/image/ngocxshawn3.webp`,
    ngocxshawn4: `${IMAGE_BASE_URL}/image/ngocxshawn4.webp`,
    ngocxshawn5: `${IMAGE_BASE_URL}/image/ngocxshawn5.webp`,
    ngocxshawn6: `${IMAGE_BASE_URL}/image/ngocxshawn6.webp`,
    ngocxshawn7: `${IMAGE_BASE_URL}/image/ngocxshawn7.webp`,
    ngocxshawn8: `${IMAGE_BASE_URL}/image/ngocxshawn8.webp`,
    ngocxshawn9: `${IMAGE_BASE_URL}/image/ngocxshawn9.webp`,
    ngocxshawn10: `${IMAGE_BASE_URL}/image/ngocxshawn10.webp`,
    ngocxshawn11: `${IMAGE_BASE_URL}/image/ngocxshawn11.webp`,
    ngocxshawn12: `${IMAGE_BASE_URL}/image/ngocxshawn12.webp`,
    ngocxshawn13: `${IMAGE_BASE_URL}/image/ngocxshawn13.webp`,
    ngocxshawn14: `${IMAGE_BASE_URL}/image/ngocxshawn14.webp`,
    ngocxshawn15: `${IMAGE_BASE_URL}/image/ngocxshawn15.webp`,
    ngocxshawn16: `${IMAGE_BASE_URL}/image/ngocxshawn16.webp`,

    // Ant Team gallery
    antweddingteam2: `${IMAGE_BASE_URL}/image/antweddingteam2.webp`,
    antweddingteam5: `${IMAGE_BASE_URL}/image/antweddingteam5.webp`,
    antweddingteam6: `${IMAGE_BASE_URL}/image/antweddingteam6.webp`,
    antweddingteam8: `${IMAGE_BASE_URL}/image/antweddingteam8.webp`,
    antweddingteam9: `${IMAGE_BASE_URL}/image/antweddingteam9.webp`,
    antweddingteam10: `${IMAGE_BASE_URL}/image/antweddingteam10.webp`,
    antweddingteam11: `${IMAGE_BASE_URL}/image/antweddingteam11.webp`,
    antweddingteam12: `${IMAGE_BASE_URL}/image/antweddingteam12.webp`,
    antweddingteam13: `${IMAGE_BASE_URL}/image/antweddingteam13.webp`,
    antweddingteam14: `${IMAGE_BASE_URL}/image/antweddingteam14.webp`,
    antweddingteam15: `${IMAGE_BASE_URL}/image/antweddingteam15.webp`,
    antweddingteam16: `${IMAGE_BASE_URL}/image/antweddingteam16.webp`,
    antweddingteam17: `${IMAGE_BASE_URL}/image/antweddingteam17.webp`,
    antweddingteam18: `${IMAGE_BASE_URL}/image/antweddingteam18.webp`,
    antweddingteam19: `${IMAGE_BASE_URL}/image/antweddingteam19.webp`,
    antweddingteam20: `${IMAGE_BASE_URL}/image/antweddingteam20.webp`,
    antweddingteam21: `${IMAGE_BASE_URL}/image/antweddingteam21.webp`,
    antweddingteam22: `${IMAGE_BASE_URL}/image/antweddingteam22.webp`,
    antweddingteam23: `${IMAGE_BASE_URL}/image/antweddingteam23.webp`,
    antweddingteam24: `${IMAGE_BASE_URL}/image/antweddingteam24.webp`,
    antweddingteam25: `${IMAGE_BASE_URL}/image/antweddingteam25.webp`,
}
